version: '2'

services: 
  app-server:
    image: 'gold-pocket-be:latest'
    build: 
      context: .
    container_name: gold-pocket-be
    ports: 
      - 8080:8080
    depends_on: 
      - db
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gold_pocket
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=administrator
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks: 
      - backend
      - frontend

  # Front End Service
  app-client:
    image: 'gold-pocket-fe:latest'
    build: .
    ports: 
      - 80:80
    container_name: gold-pocket-fe
    restart: always
    depends_on: 
      - app-server
    networks: 
      - frontend
    links: 
      - app-server
    
  #DB
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgre-SQL
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=administrator
    networks: 
      - backend
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

#NET
networks: 
  backend:
  frontend: